config/routes.rb
AmoebaCircus::Application.routes.draw do

  resources :amoebas
  get '/amoebas/:id/split' => 'amoebas#split'
  resources :acts

end

app/models/act.rb
class Act < ActiveRecord::Base
	has_many :amoebas
	has_many :talents, through: :amoebas 
end 

app/models/amoeba.rb
class Amoeba < ActiveRecord::Base
	attr_accessible :name, :generation, :talent_id, :act_id 
	belongs_to :acts
	belongs_to :talents

	NAMES = ["Keith", "Kate", "Uzo", "Anisha"]

	def split 
		Amoeba.create(name: NAMES.sample, :generation => (generation+1), :talent_id => talent_id, :act_id => act_id)
		Amoeba.create(name: NAMES.sample, :generation => (generation+1), :talent_id => talent_id, :act_id => act_id)
		destroy
	end 
end 

app/models/talent.rb
class Talent < ActiveRecord::Base
	has_many :amoebas
end 

app/controllers/act_controller.rb
class ActController < ApplicationController
	def index 
		@act = Act.all
	end 

	def show
		@act = Act.find(params[:id])
	end 

	def new
		@act = Act.new 
	end 

	def edit 
		@act = Act.find(params[:id])
	end 

	def update 
		@act = Act.find(params[:id])
		@act.update_attributes(params[:act])
		redirect_to @act
	end 

	def create 
		@act = Act.new(params[:act])
		@act.save
		redirect_to @act
	end 

	def destroy 
		@act = Act.find(params[:id])
		@act.destroy
	end 
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
	def index 
		@acts = Act.all
	end 

	def show
		@act = Act.find(params[:id])
	end 

	def new
		@act = Act.new 
	end 

	def edit 
		@act = Act.find(params[:id])
	end 

	def update 
		@act = Act.find(params[:id])
		@act.update_attributes(params[:act])
		redirect_to @act
	end 

	def create 
		@act = Act.new(params[:act])
		@act.save
		redirect_to @act
	end 

	def destroy 
		@act = Act.find(params[:id])
		@act.destroy
		redirect_to @act
	end 
end

app/controllers/amoeba_controller.rb
class AmoebaController < ApplicationController
	def index 
		@amoebas = Amoeba.all
	end 

	def show
		@amoeba = Amoeba.find(params[:id])
	end 

	def new
		@amoeba = Amoeba.new 
	end 

	def edit 
		@amoeba = Amoeba.find(params[:id])
	end 

	def update 
		@amoeba = Amoeba.find(params[:id])
		@amoeba.update_attributes(params[:amoeba])
		redirect_to @amoeba
	end 

	def create 
		@amoeba = Amoeba.new(params[:amoeba])
		@amoeba.save
		redirect_to @amoeba
	end 

	def destroy 
		@amoeba = Amoeba.find(params[:id])
		@amoeba.destroy
	end 

end

app/controllers/amoebas_controller.rb
class AmoebasController < ApplicationController
	def index 
		@amoebas = Amoeba.all
	end 

	def show
		@amoeba = Amoeba.find(params[:id])
	end 

	def new
		@amoeba = Amoeba.new 
	end 

	def edit 
		@amoeba = Amoeba.find(params[:id])
	end 

	def update 
		@amoeba = Amoeba.find(params[:id])
		@amoeba.update_attributes(params[:amoeba])
		redirect_to @amoeba
	end 

	def create 
		@amoeba = Amoeba.new(params[:amoeba])
		@amoeba.save
		redirect_to @amoeba
	end 

	def destroy 
		@amoeba = Amoeba.find(params[:id])
		@amoeba.destroy
		redirect_to @amoeba 
	end 

	def split
		@amoeba = Amoeba.find(params[:id]) 
		@amoeba.split
		redirect_to '/amoebas'
	end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/act_helper.rb
module ActHelper
end

app/helpers/amoeba_helper.rb
module AmoebaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acts/_form.html.haml
= form_for @act do |f|
	.field 
		= f.label :name
		= f.text_field :name 
	.field 
		= f.label :date 
		= f.text_field :date
	.field 
		= f.label :time 
		= f.text_field :time
	.actions 
		= f.submit 'Save'

app/views/acts/edit.html.haml
%h1="Editing #{@act.name}"

= render 'form'
= link_to 'Show', @act
= link_to 'Back', acts_path

app/views/acts/index.html.haml
%h1 Listing Acts
%table 
	%tr 
		%th Name 
		%th Date 
		%th Time
		%th Show 
		%th Edit 
		%th Delete

	- @acts.each do |act|
		%tr
			%td= act.name 
			%td= act.date 
			%td= act.time
			%td= link_to 'Show', act 
			%td= link_to 'Edit', edit_act_path(act)
			%td= link_to 'Delete', act, :method => :delete, :data => {:confirm => 'Are you sure'}
	%br 

= link_to 'New Post', new_act_path

app/views/acts/new.html.haml
%h1 New Act
= render 'form'
= link_to 'Back', acts_path

app/views/acts/show.html.haml
%h1 
	= @act.name 
%ul 
	%li= "Date: #{@act.date}"
	%li= "Time: #{@act.time}"

=link_to("Back", acts_path)

app/views/amoebas/_form.html.haml
= form_for @amoeba do |f|
	.field 
		= f.label :name 
		= f.text_area :name 
	.field 
		= f.label :talent_id
		= f.number_field :talent_id
	.field 
		= f.label :act_id 
		= f.number_field :act_id
	.actions 
		= f.submit 'Save'

app/views/amoebas/edit.html.haml
%h1 Editing Amoeba 

= render 'form'
= link_to 'Show', @amoeba 
= link_to 'Back', amoebas_path

app/views/amoebas/index.html.haml
%h1 Listing Amoebas
%table 
	%tr 
		%th Name 
		%th Generation 
		%th Talent ID
		%th Act ID 
		%th Show 
		%th Edit 
		%th Delete
		%th Split

	- @amoebas.each do |amoeba|
		%tr
			%td= amoeba.name 
			%td= amoeba.generation 
			%td= amoeba.talent_id
			%td= amoeba.act_id
			%td= link_to 'Show', amoeba 
			%td= link_to 'Edit', edit_amoeba_path(amoeba)
			%td= link_to 'Delete', amoeba, :method => :delete, :data => {:confirm => 'Are you sure'}
			%td= link_to 'Split', "/amoebas/#{amoeba.id}/split"
%br 
= link_to 'New Post', new_amoeba_path

app/views/amoebas/new.html.haml
%h1 New Amoeba
= render 'form'
= link_to 'Back', amoebas_path

app/views/amoebas/show.html.haml
%h1 
	= @amoeba.name 
%ul 
	%li= "Generation #{@amoeba.generation}"
	%li= "Talent Id #{@amoeba.talent_id}"
	%li= "Act Id #{@amoeba.act_id}"

=link_to("Back", amoebas_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmoebaCircus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>